engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Naming/ShortVariable:
        enabled: false
        exceptions: id, db
  phpcodesniffer:
    enabled: true
  phan:
    enabled: true
    config:
      ignore-undeclared: true
      dead-code-detection: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- test/
- vendor/
- public_source/js/lib/
- public_html/js/
- public_html/css/
- application/language
- config
- module/Application/language
- module/Application/config
