sudo: required
language: generic
services:
  - docker
before_install:
  - docker pull $DOCKER_REPO
  - docker build -t $DOCKER_REPO .
  - docker-compose -f module/Application/test/_files/docker-compose.yml up -d
  - docker exec -it autowp_test_web bash -c "./wait-for-it.sh autowp_test_mysql:3306"
  - docker exec -it autowp_test_mysql bash -c "mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -uroot -ppassword mysql"
  - docker exec -it autowp_test_mysql bash -c "mysql -uroot -ppassword -e 'create database autowp_test;'"
  - docker exec -it autowp_test_mysql bash -c "mysql -uroot -ppassword -e \"GRANT ALL PRIVILEGES ON autowp_test.* TO autowp_test@'%' IDENTIFIED BY 'test';\""
  - docker exec -i autowp_test_mysql bash -c "mysql -uroot -ppassword" < module/Application/test/_files/dump.sql
  
script: docker exec -it autowp_test_web sh -c "vendor/bin/phpunit  --coverage-clover ./logs/clover.xml"

after_success:
  - docker exec -it autowp_test_web bash -c "./vendor/bin/coveralls -v"
  - docker exec -it autowp_test_web bash -c "./vendor/bin/test-reporter -v --coverage-report=./logs/clover.xml"
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $DOCKER_REPO;
    fi