web:
  image: autowp/autowp
  container_name: autowp_test_web
  restart: always
  environment:
    CODECLIMATE_REPO_TOKEN: ${CODECLIMATE_REPO_TOKEN}
    TRAVIS: ${TRAVIS}
    TRAVIS_JOB_ID: ${TRAVIS_JOB_ID}
    TRAVIS_JOB_NUMBER: ${TRAVIS_JOB_NUMBER}
    TRAVIS_BRANCH: ${TRAVIS_BRANCH}
    TRAVIS_PULL_REQUEST: ${TRAVIS_PULL_REQUEST}
    TRAVIS_PULL_REQUEST_BRANCH: ${TRAVIS_PULL_REQUEST_BRANCH}
    TRAVIS_PULL_REQUEST_SHA: ${TRAVIS_PULL_REQUEST_SHA}
    TRAVIS_BUILD_NUMBER: ${TRAVIS_BUILD_NUMBER}
    TRAVIS_COMMIT: ${TRAVIS_COMMIT}
    TRAVIS_COMMIT_MESSAGE: ${TRAVIS_COMMIT_MESSAGE}
    TRAVIS_COMMIT_RANGE: ${TRAVIS_COMMIT_RANGE}
    TRAVIS_EVENT_TYPE: ${TRAVIS_EVENT_TYPE}
    TRAVIS_TAG: ${TRAVIS_TAG}
    AUTOWP_DB_HOST: "autowp_test_mysql"
    AUTOWP_DB_USERNAME: "autowp_test"
    AUTOWP_DB_PASSWORD: "test"
    AUTOWP_DB_DBNAME: "autowp_test"
    AUTOWP_USERS_SALT: "users-salt"
    AUTOWP_EMAIL_SALT: "email-salt"
    AUTOWP_MEMCACHED_HOST: "autowp_test_memcached"
    AUTOWP_HOST: "localhost"
    AUTOWP_HOST_RU: "localhost"
    AUTOWP_PICTURES_HOST: "i.localhost"
    AUTOWP_HOST_COOKIE_RU: ""
    AUTOWP_MOSTS_MIN_VEHICLES_COUNT: 1
    AUTOWP_MAIL_TYPE: "in-memory"
    AUTOWP_MAIL_SMTP_HOST: ""
    AUTOWP_MAIL_SMTP_USERNAME: ""
    AUTOWP_MAIL_SMTP_PASSWORD: ""
    AUTOWP_TELEGRAM_ACCESS_TOKEN: ""
    AUTOWP_TELEGRAM_TOKEN: ""
    AUTOWP_TWITTER_USERNAME: ""
    AUTOWP_TWITTER_OAUTH_KEY: ""
    AUTOWP_TWITTER_OAUTH_SECRET: ""
    AUTOWP_TWITTER_TOKEN_OAUTH: ""
    AUTOWP_TWITTER_TOKEN_OAUTH_SECRET: ""
    AUTOWP_FACEBOOK_APP_ID: ""
    AUTOWP_FACEBOOK_APP_SECRET: ""
    AUTOWP_FACEBOOK_PAGE_ACCESS_TOKEN: ""
    AUTOWP_YANDEX_SECRET: ""
    AUTOWP_YANDEX_PRICE: "1"
    AUTOWP_VK_TOKEN: ""
    AUTOWP_VK_OWNER_ID: ""
    AUTOWP_ELS_VK_CLIENTID: "vk_test_clientid"
    AUTOWP_ELS_VK_SECRET: "vk_test_secret"
    AUTOWP_ELS_GOOGLEPLUS_CLIENTID: "google_test_clientid"
    AUTOWP_ELS_GOOGLEPLUS_SECRET: "google_test_secret"
    AUTOWP_ELS_TWITTER_CLIENTID: "twitter_test_clientid"
    AUTOWP_ELS_TWITTER_SECRET: "twitter_test_secret"
    AUTOWP_ELS_FACEBOOK_CLIENTID: "facebook_test_clientid"
    AUTOWP_ELS_FACEBOOK_SECRET: "facebook_test_secret"
    AUTOWP_ELS_GITHUB_CLIENTID: "github_test_clientid"
    AUTOWP_ELS_GITHUB_SECRET: "github_test_secret"
    AUTOWP_ELS_LINKEDIN_CLIENTID: "linkedin_test_clientid"
    AUTOWP_ELS_LINKEDIN_SECRET: "linkedin_test_secret"
    AUTOWP_CAPTCHA: 0
    AUTOWP_RECAPTCHA_PUBLICKEY: "public"
    AUTOWP_RECAPTCHA_PRIVATEKEY: "private"
  volumes:
  - ./config/autoload/local.php:/app/config/autoload/local.php:ro
  - ./module/Application/test/_files/image:/app/public_html/image
  - ./module/Application/test/_files/pictures:/app/public_html/pictures
  links:
  - memcached
  - mysql
  
memcached:
  image: memcached
  container_name: autowp_test_memcached
  restart: always
  expose:
  - "11211"
  
mysql:
  image: mysql
  container_name: autowp_test_mysql
  restart: always
  environment:
  - "MYSQL_ROOT_PASSWORD=password"
  expose:
  - "3306"
