web:
  image: autowp/autowp
  container_name: autowp_test_web
  restart: always
  environment:
    AUTOWP_DB_HOST: "autowp_test_mysql"
    AUTOWP_DB_PORT: "3306"
    AUTOWP_DB_USERNAME: "autowp_test"
    AUTOWP_DB_PASSWORD: "test"
    AUTOWP_DB_DBNAME: "autowp_test"
    AUTOWP_USERS_SALT: "users-salt"
    AUTOWP_EMAIL_SALT: "email-salt"
    AUTOWP_MEMCACHED_HOST: "autowp_test_memcached"
    AUTOWP_HOST: "localhost"
    AUTOWP_HOST_RU: "ru.localhost"
    AUTOWP_PICTURES_HOST: "i.localhost"
    AUTOWP_HOST_COOKIE_RU: ""
    AUTOWP_MOSTS_MIN_VEHICLES_COUNT: 1
    AUTOWP_MAIL_TYPE: "in-memory"
    AUTOWP_MAIL_SMTP_HOST: ""
    AUTOWP_MAIL_SMTP_USERNAME: ""
    AUTOWP_MAIL_SMTP_PASSWORD: ""
    AUTOWP_TELEGRAM_ACCESS_TOKEN: ""
    AUTOWP_TELEGRAM_TOKEN: ""
    AUTOWP_TWITTER_USERNAME: ""
    AUTOWP_TWITTER_OAUTH_KEY: ""
    AUTOWP_TWITTER_OAUTH_SECRET: ""
    AUTOWP_TWITTER_TOKEN_OAUTH: ""
    AUTOWP_TWITTER_TOKEN_OAUTH_SECRET: ""
    AUTOWP_FACEBOOK_APP_ID: ""
    AUTOWP_FACEBOOK_APP_SECRET: ""
    AUTOWP_FACEBOOK_PAGE_ACCESS_TOKEN: ""
    AUTOWP_YANDEX_SECRET: ""
    AUTOWP_YANDEX_PRICE: "1"
    AUTOWP_VK_TOKEN: ""
    AUTOWP_VK_OWNER_ID: ""
    AUTOWP_ELS_VK_CLIENTID: "vk_test_clientid"
    AUTOWP_ELS_VK_SECRET: "vk_test_secret"
    AUTOWP_ELS_GOOGLEPLUS_CLIENTID: "google_test_clientid"
    AUTOWP_ELS_GOOGLEPLUS_SECRET: "google_test_secret"
    AUTOWP_ELS_TWITTER_CLIENTID: "twitter_test_clientid"
    AUTOWP_ELS_TWITTER_SECRET: "twitter_test_secret"
    AUTOWP_ELS_FACEBOOK_CLIENTID: "facebook_test_clientid"
    AUTOWP_ELS_FACEBOOK_SECRET: "facebook_test_secret"
    AUTOWP_ELS_GITHUB_CLIENTID: "github_test_clientid"
    AUTOWP_ELS_GITHUB_SECRET: "github_test_secret"
    AUTOWP_ELS_LINKEDIN_CLIENTID: "linkedin_test_clientid"
    AUTOWP_ELS_LINKEDIN_SECRET: "linkedin_test_secret"
    AUTOWP_CAPTCHA: 0
    AUTOWP_RECAPTCHA_PUBLICKEY: "public"
    AUTOWP_RECAPTCHA_PRIVATEKEY: "private"
    AUTOWP_GO_LISTEN: ":81"
    ONESKYAPP_KEY: "2a1C12oZU5VIK409AJd0xUfVntGyhLWa"
    ONESKYAPP_SECRET: ""
    ONESKYAPP_PROJECT_ID: 129670
    ROLLBAR_ACCESS_TOKEN: ""
    ROLLBAR_CLIENT_ACCESS_TOKEN: ""
    ROLLBAR_ENVIRONMENT: development
  volumes:
  - ./config:/app/config
  - ./data:/app/data
  - ./cache:/app/cache
  - ./assets:/app/assets
  - ./module:/app/module
  - ./public_html:/app/public_html
  - ./vendor:/app/vendor
  - ./etc/nginx/conf.d:/etc/nginx/conf.d
  #- ./goautowp:/app/goautowp
  ports:
  - "80:80"
  links:
  - memcached
  - mysql:5.7
  - frontend

memcached:
  image: memcached
  container_name: autowp_test_memcached
  restart: always
  expose:
  - "11211"

mysql:
  image: mysql:5.7
  container_name: autowp_test_mysql
  restart: always
  environment:
  - MYSQL_ROOT_PASSWORD=password
  - MYSQL_DATABASE=autowp_test
  - MYSQL_USER=autowp_test
  - MYSQL_PASSWORD=test
  volumes:
  - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
  - "./mysql:/var/lib/mysql"
  - "./mysql.conf.d:/etc/mysql/conf.d"
  expose:
  - "3306"
  ports:
  - "3306:3306"

frontend:
  image: autowp/autowp-frontend
  container_name: autowp_test_frontend
  restart: always
  volumes:
  - "./public_html/ng:/usr/share/nginx/html/ng"
