web:
  image: autowp/autowp
  container_name: autowp_test_web
  volumes:
  - ./config:/app/config
  - ./data:/app/data
  - ./cache:/app/cache
  - ./module:/app/module
  - ./public_html:/app/public_html
  - ./vendor:/app/vendor
  ports:
  - "80:80"
  restart: always
  links:
  - memcached
  - mysql
  
memcached:
  image: memcached
  container_name: autowp_test_memcached
  expose:
  - "11211"
  
mysql:
  image: mysql
  container_name: autowp_test_mysql
  environment:
  - "MYSQL_ROOT_PASSWORD=password"
  volumes:
  - "./mysql:/var/lib/mysql"
  - "./mysql.conf.d:/etc/mysql/conf.d"
  expose:
  - "3306"
